name: BetterCrates
version: '${project.version}'
main: me.hsgamer.bettercrates.BetterCrates
api-version: 1.13
authors: [ HSGamer ]
softdepend:
  - ItemBridge
  - DecentHolograms
  - HolographicDisplays